ALTER TABLE abuse_mailbox DROP COLUMN thread_id;
ALTER TABLE admin_c DROP COLUMN thread_id;
ALTER TABLE as_block DROP COLUMN thread_id;
ALTER TABLE as_set DROP COLUMN thread_id;
ALTER TABLE aut_num DROP COLUMN thread_id;
ALTER TABLE auth DROP COLUMN thread_id;
DROP TABLE auth_override;
ALTER TABLE author DROP COLUMN thread_id;
ALTER TABLE domain DROP COLUMN thread_id;
ALTER TABLE ds_rdata DROP COLUMN thread_id;
ALTER TABLE e_mail DROP COLUMN thread_id;
ALTER TABLE filter_set DROP COLUMN thread_id;
ALTER TABLE fingerpr DROP COLUMN thread_id;
ALTER TABLE form DROP COLUMN thread_id;
ALTER TABLE history DROP COLUMN thread_id, DROP COLUMN serial, DROP COLUMN prev_serial;
ALTER TABLE ifaddr DROP COLUMN thread_id;
ALTER TABLE inaddr_arpa DROP COLUMN thread_id;
ALTER TABLE inet6num DROP COLUMN thread_id;
ALTER TABLE inet_rtr DROP COLUMN thread_id;
ALTER TABLE inetnum DROP COLUMN thread_id;
ALTER TABLE interface DROP COLUMN thread_id;
ALTER TABLE ip6int DROP COLUMN thread_id;
ALTER TABLE irt DROP COLUMN thread_id;
ALTER TABLE irt_nfy DROP COLUMN thread_id;
ALTER TABLE key_cert DROP COLUMN thread_id;
ALTER TABLE last DROP COLUMN thread_id, DROP COLUMN serial, DROP COLUMN prev_serial;
DROP TABLE limerick;
ALTER TABLE mbrs_by_ref DROP COLUMN thread_id;
ALTER TABLE member_of DROP COLUMN thread_id;
ALTER TABLE mnt_by DROP COLUMN thread_id;
ALTER TABLE mnt_domains DROP COLUMN thread_id;
ALTER TABLE mnt_irt DROP COLUMN thread_id;
ALTER TABLE mnt_lower DROP COLUMN thread_id;
ALTER TABLE mnt_nfy DROP COLUMN thread_id;
ALTER TABLE mnt_ref DROP COLUMN thread_id;
ALTER TABLE mnt_routes DROP COLUMN thread_id;
DROP TABLE mnt_routes6;
ALTER TABLE mntner DROP COLUMN thread_id;
ALTER TABLE names DROP COLUMN thread_id;
ALTER TABLE nic_hdl DROP COLUMN thread_id;
ALTER TABLE notify DROP COLUMN thread_id;
ALTER TABLE nserver DROP COLUMN thread_id;
ALTER TABLE org DROP COLUMN thread_id;
ALTER TABLE org_name DROP COLUMN thread_id;
ALTER TABLE organisation DROP COLUMN thread_id;
ALTER TABLE organisation_id DROP COLUMN thread_id;
ALTER TABLE peering_set DROP COLUMN thread_id;
ALTER TABLE person_role DROP COLUMN thread_id;
ALTER TABLE ping_hdl DROP COLUMN thread_id;
ALTER TABLE poetic_form DROP COLUMN thread_id;
ALTER TABLE ref_nfy DROP COLUMN thread_id;
ALTER TABLE refer DROP COLUMN thread_id;
ALTER TABLE referral_by DROP COLUMN thread_id;
DROP TABLE rev_srv;
ALTER TABLE route DROP COLUMN thread_id;
ALTER TABLE route6 DROP COLUMN thread_id;
ALTER TABLE route_set DROP COLUMN thread_id;
ALTER TABLE rtr_set DROP COLUMN thread_id;
ALTER TABLE serials DROP COLUMN thread_id;
DROP TABLE sub_dom;
ALTER TABLE tech_c DROP COLUMN thread_id;
ALTER TABLE upd_to DROP COLUMN thread_id;
ALTER TABLE x509 DROP COLUMN thread_id;
ALTER TABLE zone_c DROP COLUMN thread_id;

UPDATE version SET version = 'whois-1.70';
