package spec.integration

import net.ripe.db.whois.common.IntegrationTest
import spec.domain.SyncUpdate

@org.junit.experimental.categories.Category(IntegrationTest.class)
class HelpIntegrationSpec extends BaseWhoisSourceSpec {

    @Override
    Map<String, String> getFixtures() {
        return Collections.emptyMap()
    }

    def "send help message"() {
      when:
        def response = syncUpdate new SyncUpdate(help: true)
      then:
        response =~ "You have requested Help information from the RIPE NCC Database"
        response =~ "Generated by RIPE WHOIS Update version "
        response =~ "sync update"
    }
}
