//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.27 at 10:01:46 AM EST 
//


package net.ripe.db.whois.api.whois.rdap.domain.vcard;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import net.ripe.db.whois.api.whois.rdap.VcardObject;


/**
 * <p>Java class for adrEntryValueType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="adrEntryValueType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="adr1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="adr2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="adr3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="adr4" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="adr5" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="adr6" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="adr7" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "adrEntryValueType", propOrder = {
    "adr1",
    "adr2",
    "adr3",
    "adr4",
    "adr5",
    "adr6",
    "adr7"
})
public class AdrEntryValueType
    extends VcardObject
    implements Serializable
{

    @XmlElement(required = true, defaultValue = "")
    protected String adr1;
    @XmlElement(required = true, defaultValue = "")
    protected String adr2;
    @XmlElement(required = true, defaultValue = "")
    protected String adr3;
    @XmlElement(required = true, defaultValue = "")
    protected String adr4;
    @XmlElement(required = true, defaultValue = "")
    protected String adr5;
    @XmlElement(required = true, defaultValue = "")
    protected String adr6;
    @XmlElement(required = true, defaultValue = "")
    protected String adr7;

    /**
     * Sets the value of the adr1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdr1(String value) {
        this.adr1 = value;
    }

    /**
     * Sets the value of the adr2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdr2(String value) {
        this.adr2 = value;
    }

    /**
     * Sets the value of the adr3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdr3(String value) {
        this.adr3 = value;
    }

    /**
     * Sets the value of the adr4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdr4(String value) {
        this.adr4 = value;
    }

    /**
     * Sets the value of the adr5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdr5(String value) {
        this.adr5 = value;
    }

    /**
     * Sets the value of the adr6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdr6(String value) {
        this.adr6 = value;
    }

    /**
     * Sets the value of the adr7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdr7(String value) {
        this.adr7 = value;
    }

    /**
     * Gets the value of the adr1 property.
     * 
     */
    public String getAdr1() {
        if (null == adr1) {
            return "";
        }
        return adr1;
    }

    /**
     * Gets the value of the adr2 property.
     * 
     */
    public String getAdr2() {
        if (null == adr2) {
            return "";
        }
        return adr2;
    }

    /**
     * Gets the value of the adr3 property.
     * 
     */
    public String getAdr3() {
        if (null == adr3) {
            return "";
        }
        return adr3;
    }

    /**
     * Gets the value of the adr4 property.
     * 
     */
    public String getAdr4() {
        if (null == adr4) {
            return "";
        }
        return adr4;
    }

    /**
     * Gets the value of the adr5 property.
     * 
     */
    public String getAdr5() {
        if (null == adr5) {
            return "";
        }
        return adr5;
    }

    /**
     * Gets the value of the adr6 property.
     * 
     */
    public String getAdr6() {
        if (null == adr6) {
            return "";
        }
        return adr6;
    }

    /**
     * Gets the value of the adr7 property.
     * 
     */
    public String getAdr7() {
        if (null == adr7) {
            return "";
        }
        return adr7;
    }

}
