//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.27 at 03:38:16 PM EST
//


package net.ripe.db.whois.api.whois.rdap.domain.vcard;

import net.ripe.db.whois.api.whois.rdap.VcardObject;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for adrEntryValueType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="adrEntryValueType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pobox" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ext" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="street" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="locality" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="region" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "adrEntryValueType", propOrder = {
    "pobox",
    "ext",
    "street",
    "locality",
    "region",
    "code",
    "country"
})
public class AdrEntryValueType
    extends VcardObject
    implements Serializable
{

    @XmlElement(defaultValue = "")
    protected String pobox;
    @XmlElement(defaultValue = "")
    protected String ext;
    @XmlElement(defaultValue = "")
    protected String street;
    @XmlElement(defaultValue = "")
    protected String locality;
    @XmlElement(defaultValue = "")
    protected String region;
    @XmlElement(defaultValue = "")
    protected String code;
    @XmlElement(defaultValue = "")
    protected String country;

    /**
     * Sets the value of the pobox property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPobox(String value) {
        this.pobox = value;
    }

    /**
     * Sets the value of the ext property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setExt(String value) {
        this.ext = value;
    }

    /**
     * Sets the value of the street property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setStreet(String value) {
        this.street = value;
    }

    /**
     * Sets the value of the locality property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLocality(String value) {
        this.locality = value;
    }

    /**
     * Sets the value of the region property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRegion(String value) {
        this.region = value;
    }

    /**
     * Sets the value of the code property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Sets the value of the country property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the pobox property.
     *
     */
    public String getPobox() {
        if (null == pobox) {
            return "";
        }
        return pobox;
    }

    /**
     * Gets the value of the ext property.
     *
     */
    public String getExt() {
        if (null == ext) {
            return "";
        }
        return ext;
    }

    /**
     * Gets the value of the street property.
     *
     */
    public String getStreet() {
        if (null == street) {
            return "";
        }
        return street;
    }

    /**
     * Gets the value of the locality property.
     *
     */
    public String getLocality() {
        if (null == locality) {
            return "";
        }
        return locality;
    }

    /**
     * Gets the value of the region property.
     *
     */
    public String getRegion() {
        if (null == region) {
            return "";
        }
        return region;
    }

    /**
     * Gets the value of the code property.
     *
     */
    public String getCode() {
        if (null == code) {
            return "";
        }
        return code;
    }

    /**
     * Gets the value of the country property.
     *
     */
    public String getCountry() {
        if (null == country) {
            return "";
        }
        return country;
    }

}
