//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: stripped
//


package net.ripe.db.whois.api.whois.rdap.domain.vcard;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import net.ripe.db.whois.api.whois.rdap.VcardObject;


/**
 * <p>Java class for nValueType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="nValueType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="surname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="given" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="prefix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="suffix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="honorifics" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="prefix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="suffix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "nValueType", propOrder = {
    "surname",
    "given",
    "prefix",
    "suffix",
    "honorifics"
})
public class NValueType
    extends VcardObject
    implements Serializable
{

    @XmlElement(defaultValue = "")
    protected String surname;
    @XmlElement(defaultValue = "")
    protected String given;
    @XmlElement(defaultValue = "")
    protected String prefix;
    @XmlElement(defaultValue = "")
    protected String suffix;
    protected NValueType.Honorifics honorifics = new NValueType.Honorifics();

    /**
     * Sets the value of the surname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSurname(String value) {
        this.surname = value;
    }

    /**
     * Sets the value of the given property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGiven(String value) {
        this.given = value;
    }

    /**
     * Sets the value of the prefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrefix(String value) {
        this.prefix = value;
    }

    /**
     * Sets the value of the suffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuffix(String value) {
        this.suffix = value;
    }

    /**
     * Gets the value of the honorifics property.
     * 
     * @return
     *     possible object is
     *     {@link NValueType.Honorifics }
     *     
     */
    public NValueType.Honorifics getHonorifics() {
        return honorifics;
    }

    /**
     * Sets the value of the honorifics property.
     * 
     * @param value
     *     allowed object is
     *     {@link NValueType.Honorifics }
     *     
     */
    public void setHonorifics(NValueType.Honorifics value) {
        this.honorifics = value;
    }

    /**
     * Gets the value of the surname property.
     * 
     */
    public String getSurname() {
        if (null == surname) {
            return "";
        }
        return surname;
    }

    /**
     * Gets the value of the given property.
     * 
     */
    public String getGiven() {
        if (null == given) {
            return "";
        }
        return given;
    }

    /**
     * Gets the value of the prefix property.
     * 
     */
    public String getPrefix() {
        if (null == prefix) {
            return "";
        }
        return prefix;
    }

    /**
     * Gets the value of the suffix property.
     * 
     */
    public String getSuffix() {
        if (null == suffix) {
            return "";
        }
        return suffix;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="prefix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="suffix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "prefix",
        "suffix"
    })
    public static class Honorifics
        extends VcardObject
        implements Serializable
    {

        @XmlElement(defaultValue = "")
        protected String prefix;
        @XmlElement(defaultValue = "")
        protected String suffix;

        /**
         * Sets the value of the prefix property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrefix(String value) {
            this.prefix = value;
        }

        /**
         * Sets the value of the suffix property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSuffix(String value) {
            this.suffix = value;
        }

        /**
         * Gets the value of the prefix property.
         * 
         */
        public String getPrefix() {
            if (null == prefix) {
                return "";
            }
            return prefix;
        }

        /**
         * Gets the value of the suffix property.
         * 
         */
        public String getSuffix() {
            if (null == suffix) {
                return "";
            }
            return suffix;
        }

    }

}
