//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: stripped
//


package net.ripe.db.whois.api.whois.rdap.domain.vcard;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.ripe.db.whois.api.whois.rdap.domain.vcard package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.ripe.db.whois.api.whois.rdap.domain.vcard
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Role }
     * 
     */
    public Role createRole() {
        return new Role();
    }

    /**
     * Create an instance of {@link Lang }
     * 
     */
    public Lang createLang() {
        return new Lang();
    }

    /**
     * Create an instance of {@link Bday }
     * 
     */
    public Bday createBday() {
        return new Bday();
    }

    /**
     * Create an instance of {@link Org }
     * 
     */
    public Org createOrg() {
        return new Org();
    }

    /**
     * Create an instance of {@link Tz }
     * 
     */
    public Tz createTz() {
        return new Tz();
    }

    /**
     * Create an instance of {@link Tel }
     * 
     */
    public Tel createTel() {
        return new Tel();
    }

    /**
     * Create an instance of {@link N }
     * 
     */
    public N createN() {
        return new N();
    }

    /**
     * Create an instance of {@link Email }
     * 
     */
    public Email createEmail() {
        return new Email();
    }

    /**
     * Create an instance of {@link Fn }
     * 
     */
    public Fn createFn() {
        return new Fn();
    }

    /**
     * Create an instance of {@link AdrEntryValueType }
     * 
     */
    public AdrEntryValueType createAdrEntryValueType() {
        return new AdrEntryValueType();
    }

    /**
     * Create an instance of {@link NValueType }
     * 
     */
    public NValueType createNValueType() {
        return new NValueType();
    }

    /**
     * Create an instance of {@link Logo }
     * 
     */
    public Logo createLogo() {
        return new Logo();
    }

    /**
     * Create an instance of {@link Anniversary }
     * 
     */
    public Anniversary createAnniversary() {
        return new Anniversary();
    }

    /**
     * Create an instance of {@link Version }
     * 
     */
    public Version createVersion() {
        return new Version();
    }

    /**
     * Create an instance of {@link Vcard }
     * 
     */
    public Vcard createVcard() {
        return new Vcard();
    }

    /**
     * Create an instance of {@link Title }
     * 
     */
    public Title createTitle() {
        return new Title();
    }

    /**
     * Create an instance of {@link Note }
     * 
     */
    public Note createNote() {
        return new Note();
    }

    /**
     * Create an instance of {@link Caladruri }
     * 
     */
    public Caladruri createCaladruri() {
        return new Caladruri();
    }

    /**
     * Create an instance of {@link Url }
     * 
     */
    public Url createUrl() {
        return new Url();
    }

    /**
     * Create an instance of {@link Kind }
     * 
     */
    public Kind createKind() {
        return new Kind();
    }

    /**
     * Create an instance of {@link Categories }
     * 
     */
    public Categories createCategories() {
        return new Categories();
    }

    /**
     * Create an instance of {@link Caluri }
     * 
     */
    public Caluri createCaluri() {
        return new Caluri();
    }

    /**
     * Create an instance of {@link Gender }
     * 
     */
    public Gender createGender() {
        return new Gender();
    }

    /**
     * Create an instance of {@link Key }
     * 
     */
    public Key createKey() {
        return new Key();
    }

    /**
     * Create an instance of {@link Birth }
     * 
     */
    public Birth createBirth() {
        return new Birth();
    }

    /**
     * Create an instance of {@link Geo }
     * 
     */
    public Geo createGeo() {
        return new Geo();
    }

    /**
     * Create an instance of {@link Adr }
     * 
     */
    public Adr createAdr() {
        return new Adr();
    }

    /**
     * Create an instance of {@link Nickname }
     * 
     */
    public Nickname createNickname() {
        return new Nickname();
    }

    /**
     * Create an instance of {@link NValueType.Honorifics }
     * 
     */
    public NValueType.Honorifics createNValueTypeHonorifics() {
        return new NValueType.Honorifics();
    }

}
