name: 'Auto Assign'
on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  runs-on: ubuntu-latest
  steps:
    - name: "Assign Team and Persons"
      uses: delivery-much/actions-assigner@v1
      with:
        token: ${{ secrets.PAT_AUTO_REVIEW_ACTION }}
        org: "RIPE-NCC"
        team-reviewers: "database"
