//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: stripped
//


package net.ripe.db.whois.api.whois.rdap.domain;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.ripe.db.whois.api.whois.rdap.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.ripe.db.whois.api.whois.rdap.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Nameservers.IpAddresses }
     * 
     */
    public Nameservers.IpAddresses createNameserversIpAddresses() {
        return new Nameservers.IpAddresses();
    }

    /**
     * Create an instance of {@link Domain }
     * 
     */
    public Domain createDomain() {
        return new Domain();
    }

    /**
     * Create an instance of {@link Ip }
     * 
     */
    public Ip createIp() {
        return new Ip();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link Nameservers }
     * 
     */
    public Nameservers createNameservers() {
        return new Nameservers();
    }

    /**
     * Create an instance of {@link Entity }
     * 
     */
    public Entity createEntity() {
        return new Entity();
    }

    /**
     * Create an instance of {@link Remarks }
     * 
     */
    public Remarks createRemarks() {
        return new Remarks();
    }

    /**
     * Create an instance of {@link Autnum }
     * 
     */
    public Autnum createAutnum() {
        return new Autnum();
    }

    /**
     * Create an instance of {@link Notices }
     * 
     */
    public Notices createNotices() {
        return new Notices();
    }

    /**
     * Create an instance of {@link Events }
     * 
     */
    public Events createEvents() {
        return new Events();
    }

    /**
     * Create an instance of {@link Links }
     * 
     */
    public Links createLinks() {
        return new Links();
    }

}
