//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.04 at 09:28:58 AM EST 
//


package net.ripe.db.whois.api.whois.rdap.domain;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.ripe.db.whois.api.whois.rdap.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Nameserver_QNAME = new QName("", "nameserver");
    private final static QName _Remark_QNAME = new QName("", "remark");
    private final static QName _Event_QNAME = new QName("", "event");
    private final static QName _Entity_QNAME = new QName("", "entity");
    private final static QName _Link_QNAME = new QName("", "link");
    private final static QName _Notice_QNAME = new QName("", "notice");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.ripe.db.whois.api.whois.rdap.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Entity }
     * 
     */
    public Entity createEntity() {
        return new Entity();
    }

    /**
     * Create an instance of {@link Ip }
     * 
     */
    public Ip createIp() {
        return new Ip();
    }

    /**
     * Create an instance of {@link Autnum }
     * 
     */
    public Autnum createAutnum() {
        return new Autnum();
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link Link }
     * 
     */
    public Link createLink() {
        return new Link();
    }

    /**
     * Create an instance of {@link Nameserver }
     * 
     */
    public Nameserver createNameserver() {
        return new Nameserver();
    }

    /**
     * Create an instance of {@link Remark }
     * 
     */
    public Remark createRemark() {
        return new Remark();
    }

    /**
     * Create an instance of {@link Notice }
     * 
     */
    public Notice createNotice() {
        return new Notice();
    }

    /**
     * Create an instance of {@link RdapObject }
     * 
     */
    public RdapObject createRdapObject() {
        return new RdapObject();
    }

    /**
     * Create an instance of {@link Domain }
     * 
     */
    public Domain createDomain() {
        return new Domain();
    }

    /**
     * Create an instance of {@link Nameserver.IpAddresses }
     * 
     */
    public Nameserver.IpAddresses createNameserverIpAddresses() {
        return new Nameserver.IpAddresses();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Nameserver }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "nameserver")
    public JAXBElement<Nameserver> createNameserver(Nameserver value) {
        return new JAXBElement<Nameserver>(_Nameserver_QNAME, Nameserver.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Remark }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "remark")
    public JAXBElement<Remark> createRemark(Remark value) {
        return new JAXBElement<Remark>(_Remark_QNAME, Remark.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Event }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "event")
    public JAXBElement<Event> createEvent(Event value) {
        return new JAXBElement<Event>(_Event_QNAME, Event.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Entity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "entity")
    public JAXBElement<Entity> createEntity(Entity value) {
        return new JAXBElement<Entity>(_Entity_QNAME, Entity.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Link }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "link")
    public JAXBElement<Link> createLink(Link value) {
        return new JAXBElement<Link>(_Link_QNAME, Link.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Notice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "notice")
    public JAXBElement<Notice> createNotice(Notice value) {
        return new JAXBElement<Notice>(_Notice_QNAME, Notice.class, null, value);
    }

}
