//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.26 at 10:06:18 AM EST 
//


package net.ripe.db.whois.api.whois.rdap.domain;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}nameserver" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nameserver"
})
@XmlRootElement(name = "rdap-resources")
public class RdapResources
    implements Serializable
{

    protected Nameserver nameserver;

    /**
     * Gets the value of the nameserver property.
     * 
     * @return
     *     possible object is
     *     {@link Nameserver }
     *     
     */
    public Nameserver getNameserver() {
        return nameserver;
    }

    /**
     * Sets the value of the nameserver property.
     * 
     * @param value
     *     allowed object is
     *     {@link Nameserver }
     *     
     */
    public void setNameserver(Nameserver value) {
        this.nameserver = value;
    }

}
