name: 'Auto Assign'
on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: delivery-much/actions-assigner@v1
        with:
          token: ${{ secrets.PAT_AUTO_REVIEW_ACTION }}
          team-reviewers: "RIPE-NCC/database"
