name: 'Auto Assign'
on: pull_request

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: sr-caprx/team-request-review@vX.X
        with:
          config: ".github/auto_assign.yml"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
